# Generated by Django 5.1.6 on 2025-03-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('logins', '0002_login_email_login_password_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
    ]
