# Generated by Django 5.1.6 on 2025-03-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0004_calendarevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='all_day',
            new_name='allDay',
        ),
    ]
