# Generated by Django 5.1.6 on 2025-03-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0006_poll_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(max_length=512)),
            ],
        ),
    ]
